globals:
  session_name: user
  lang: es
  salt: lastmile
development:
  scope: ''
  mail:
    assets_host: '18.111.28.209:3000'
    from: 'no-reply@feathermexico.com'
    to: 'no-reply@feathermexico.com'
  elements:
    km2: '/km2'
    loopa: '/loopa'
    compass: '/compass/front/index.php?'
production:
  scope: ''
  mail:
    assets_host: 'lastmile.mit.edu'
    from: 'no-reply@feathermexico.com'
    to: 'megacitylab-km2@mit.edu'
  elements:
    km2: '/km2'
    loopa: '/loopa/'
    compass: '/compass/front/index.php?'
